[package]
name = "rust_server"
version = "0.1.0"
authors = ["Marius Reimer <reime005@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
rocket_contrib = "0.4.5"
reqwest = { version = "0.10.6", features = ["blocking"] }
regex = "1"
lazy_static = "1.4.0"
